import OSiOSThemeDarkSizeSmall from "./OSiOSThemeDarkSizeSmall";
import PropTypes from "prop-types";
import styles from "./IPhoneAlphabetQWERTY.module.css";

const IPhoneAlphabetQWERTY = ({ className = "" }) => {
  return (
    <div className={[styles.iphoneAlphabetQwerty, className].join(" ")}>
      <div className={styles.bottomRow}>
        <OSiOSThemeDarkSizeSmall
          letter="Z"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="276px"
          oSiOSThemeDarkSizeSmallLeft="0px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="X"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="230px"
          oSiOSThemeDarkSizeSmallLeft="46px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 5px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="C"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="184px"
          oSiOSThemeDarkSizeSmallLeft="92px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="V"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="138px"
          oSiOSThemeDarkSizeSmallLeft="138px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 5px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="B"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="92px"
          oSiOSThemeDarkSizeSmallLeft="184px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="N"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="46px"
          oSiOSThemeDarkSizeSmallLeft="230px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 5px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="M"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 276px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="0px"
          oSiOSThemeDarkSizeSmallLeft="276px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
      </div>
      <div className={styles.middleRow}>
        <OSiOSThemeDarkSizeSmall
          letter="A"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 353px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="353px"
          oSiOSThemeDarkSizeSmallLeft="0px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="S"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 355px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="310px"
          oSiOSThemeDarkSizeSmallLeft="45px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="D"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 353px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="265px"
          oSiOSThemeDarkSizeSmallLeft="88px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="F"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 354px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="221px"
          oSiOSThemeDarkSizeSmallLeft="133px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="G"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 354px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="177px"
          oSiOSThemeDarkSizeSmallLeft="177px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="H"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 354px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="133px"
          oSiOSThemeDarkSizeSmallLeft="221px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="J"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 353px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="88px"
          oSiOSThemeDarkSizeSmallLeft="265px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="K"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 355px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="45px"
          oSiOSThemeDarkSizeSmallLeft="310px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="L"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 353px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="0px"
          oSiOSThemeDarkSizeSmallLeft="353px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
      </div>
      <div className={styles.topRow}>
        <OSiOSThemeDarkSizeSmall
          letter="Q"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 383px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="383px"
          oSiOSThemeDarkSizeSmallLeft="0px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="W"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 384px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="341px"
          oSiOSThemeDarkSizeSmallLeft="43px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="E"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 383px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="298px"
          oSiOSThemeDarkSizeSmallLeft="85px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="R"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 384px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="256px"
          oSiOSThemeDarkSizeSmallLeft="128px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="T"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 383px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="213px"
          oSiOSThemeDarkSizeSmallLeft="170px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="Y"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 383px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="170px"
          oSiOSThemeDarkSizeSmallLeft="213px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 4px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="U"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 384px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="128px"
          oSiOSThemeDarkSizeSmallLeft="256px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="I"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 383px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="85px"
          oSiOSThemeDarkSizeSmallLeft="298px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="O"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 384px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="43px"
          oSiOSThemeDarkSizeSmallLeft="341px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
        <OSiOSThemeDarkSizeSmall
          letter="P"
          oSiOSThemeDarkSizeSmallWidth="calc(100% - 383px)"
          oSiOSThemeDarkSizeSmallPosition="absolute"
          oSiOSThemeDarkSizeSmallTop="0px"
          oSiOSThemeDarkSizeSmallRight="0px"
          oSiOSThemeDarkSizeSmallLeft="383px"
          oSiOSThemeDarkSizeSmallHeight="43px"
          oSiOSThemeDarkSizeSmallFlex="unset"
          oSiOSThemeDarkSizeSmallDisplay="unset"
          oSiOSThemeDarkSizeSmallFlexDirection="unset"
          oSiOSThemeDarkSizeSmallPadding="unset"
          oSiOSThemeDarkSizeSmallMinWidth="unset"
          letterTop="calc(50% - 14.5px)"
          letterPosition="absolute"
          letterWidth="calc(100% - 3px)"
          letterLeft="0px"
          letterDisplay="inline-block"
          letterFlex="unset"
        />
      </div>
      <img className={styles.keysIcon} alt="" src="/-keys--icon.svg" />
      <img className={styles.keysIcon1} alt="" src="/-keys--icon1.svg" />
    </div>
  );
};

IPhoneAlphabetQWERTY.propTypes = {
  className: PropTypes.string,
};

export default IPhoneAlphabetQWERTY;
